### PR TITLE
Add a link to racket docs instead of commit.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks! I was looking at http://docs.racket-lang.org/reference/windowspaths.html which I suppose is for a released version and does not have this change yet.

**Comment by samth** [comment]
Exactly.
​

**Comment by samth** [comment]
I'll submit a PR for the stable link when we release (in a couple weeks).

**Comment by SimonSapin** [comment]
Great, thanks.

**Pull request merged**
